name: CI

on:
  push:
    branches:
      - release
  pull_request:
    branches:
      - release

jobs:
  flutter_analyze_and_build:
    name: Analyze & Build APKs
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Flutter
        uses: subosito/flutter-action@v1
        with:
          channel: "stable"

      - name: Get dependencies
        run: flutter pub get

      - name: Run flutter analyze (non-blocking)
        run: flutter analyze || true

      - name: Build APK (Release)
        run: flutter build apk --release

      - name: Upload APK Release
        uses: actions/upload-artifact@v4
        with:
          name: release-apk
          path: build/app/outputs/flutter-apk/app-release.apk

      - name: Build APK (Debug)
        run: flutter build apk --debug

      - name: Upload APK Debug
        uses: actions/upload-artifact@v4
        with:
          name: debug-apk
          path: build/app/outputs/flutter-apk/app-debug.apk
